const products = [
  {
    id: 1,
    title: 'UGRACE Backpack',
    category: 'bags',
    price: 13300,
    img: '../images/bag1.jpg',
    desc: `UGRACE Vintage Laptop Backpack with USB Charging Port, Elegant Water Resistant Travelling Backpack Casual Daypacks School Shoulder Bag for Men Women, Fits up to 15.6Inch Laptop in Grey`,
    brand: 'UGRACE',
    author: '',
  },
  {
    id: 2,
    title: 'Fjallraven Backpack',
    category: 'bags',
    price: 25774,
    img: '../images/bag2.jpg',
    desc: `Fjallraven, Kanken Classic Backpack for Everyday, Ochre`,
    brand: 'Fjallraven store',
    author: '',
  },
  {
    id: 3,
    title: 'Carhartt Backpack',
    category: 'bags',
    price: 17875,
    img: '../images/bag3.jpg',
    desc: `Carhartt Legacy Classic Work Backpack with Padded Laptop Sleeve, Carhartt Brown`,
    brand: 'Carhartt Store',
    author: '',
  },
  {
    id: 4,
    title: 'Carhartt Backpack',
    category: 'bags',
    price: 41156,
    img: '../images/bag4.jpg',
    desc: `Carhartt Legacy Deluxe Work Backpack with 17-Inch Laptop Compartment, Grey`,
    brand: 'Carhartt Store',
    author: '',
  },
  {
    id: 5,
    title: 'NOMATIC Pack',
    category: 'bags',
    price: 25774,
    img: '../images/bag5.jpg',
    desc: `NOMATIC Travel Pack- Black Water Resistant Anti-Theft 30L Flight Approved Carry on Laptop Bag Computer Backpack`,
    brand: 'NOMATIC',
    author: '',
  },
  {
    id: 6,
    title: 'Samsonite Backpack',
    category: 'bags',
    price: 58616,
    img: '../images/bag6.jpg',
    desc: `Samsonite Classic Leather Slim Backpack, Cognac, One Size`,
    brand: 'Samsonite Store',
    author: '',
  },
  {
    id: 7,
    title: 'adidas Backpack',
    category: 'bags',
    price: 19123,
    img: '../images/bag7.jpg',
    desc: `adidas Stadium II Backpack, Black, One Size`,
    brand: 'Adidas',
    author: '',
  },
  {
    id: 8,
    title: 'Shrradoo Backpack',
    category: 'bags',
    price: 16213,
    img: '../images/bag8.jpg',
    desc: `Extra Large 52L Travel Laptop Backpack with USB Charging Port Fit 17 Inch Laptops for Men Women`,
    brand: 'SHRRADOO',
    author: '',
  },
  {
    id: 9,
    title: 'Carhartt Backpack',
    category: 'bags',
    price: 27853,
    img: '../images/bag9.jpg',
    desc: `Carhartt Legacy Standard Work Backpack with Padded Laptop Sleeve and Tablet Storage, Carhartt Brown`,
    brand: 'Carhartt Store',
    author: '',
  },
  {
    id: 10,
    title: 'Asge Backpacks',
    category: 'bags',
    price: 15381,
    img: '../images/bag10.jpg',
    desc: `Asge Backpacks for Boys School Bags for Kids Luminous Bookbag and Sling Bag Set`,
    brand: 'Asge Store',
    author: '',
  },
  {
    id: 11,
    title: 'The Thursday Murder Club: A Novel',
    category: 'books',
    price: 5817,
    img: '../images/book1.jpg',
    desc: `The Thursday Murder Club
    Book 1 of 3: A Thursday Murder Club Mystery  | by Richard Osman, Lesley Manville, et al.`,
    brand: '',
    author: 'Richard Osman',
  },
  {
    id: 12,
    title: 'Surviving The Forest',
    category: 'books',
    price: 6684,
    img: '../images/book2.jpg',
    desc: `Surviving The Forest (World War II Brave Women Fiction), 
    Book 1 of 8: World War II Brave Women Fiction`,
    brand: '',
    author: 'Adiva Geffen',
  },
  {
    id: 13,
    title: 'The Dark Hours',
    category: 'books',
    price: 5817,
    img: '../images/book3.jpg',
    desc: `The Dark Hours
    Book 4 of 5: Renée Ballard  | by Michael Connelly  | Nov 9, 2021`,
    brand: '',
    author: 'Michael Connelly',
  },
  {
    id: 14,
    title: 'An Honest Lie',
    category: 'books',
    price: 9600,
    img: '../images/book4.jpg',
    desc: `An Honest Lie
    by Tarryn Fisher  | Apr 26, 2022`,
    brand: '',
    author: 'Tarryn Fisher',
  },
  {
    id: 15,
    title: 'The Stranger in the Lifeboat',
    category: 'books',
    price: 6232,
    img: '../images/book5.jpg',
    desc: `The Stranger in the Lifeboat: A Novel
    by Mitch Albom  | Nov 2, 2021`,
    brand: '',
    author: 'Mitch Albom',
  },
  {
    id: 16,
    title: 'The Match',
    category: 'books',
    price: 5817,
    img: '../images/book6.jpg',
    desc: `The Match
    Book 2 of 2: Wilde  | by Harlan Coben  | Mar 15, 2022`,
    brand: '',
    author: 'Harlan Coben',
  },
  {
    id: 17,
    title: 'Wish You Were Here',
    category: 'books',
    price: 5817,
    img: '../images/book7.jpg',
    desc: `Wish You Were Here: A Novel
    by Jodi Picoult  | Nov 30, 2021`,
    brand: '',
    author: 'Jodi Picoult',
  },
  {
    id: 18,
    title: 'The Last Thing He Told Me',
    category: 'books',
    price: 5410,
    img: '../images/book8.jpg',
    desc: `The Last Thing He Told Me: A Novel
    by Laura Dave  | May 4, 2021 `,
    brand: '',
    author: 'Laura Dave',
  },
  {
    id: 19,
    title: 'The Family Across the Street',
    category: 'books',
    price: 3739,
    img: '../images/book9.jpg',
    desc: `The Family Across the Street: A totally unputdownable psychological thriller with a shocking twist
    by Nicole Trope  | Aug 6, 2021`,
    brand: '',
    author: 'Nicole Trope',
  },
  {
    id: 20,
    title: 'Twenty Years Later',
    category: 'books',
    price: 3739,
    img: '../images/book10.jpg',
    desc: `Twenty Years Later: A Riveting New Thriller
    by Charlie Donlea  | Dec 28, 2021`,
    brand: '',
    author: 'Charlie Donlea',
  },
  {
    id: 21,
    title: 'Under Armour Sneaker',
    category: 'shoes',
    price: 10392,
    img: '../images/shoe1.jpg',
    desc: `Under Armour Unisex-Child Grade School Assert 8 Sneaker`,
    brand: 'Under Armour',
    author: '',
  },
  {
    id: 22,
    title: 'Under Armour Running Shoe',
    category: 'shoes',
    price: 6235,
    img: '../images/shoe2.jpg',
    desc: `Under Armour Unisex-Child Pre School Assert 9 Alternate Closure Running Shoe`,
    brand: 'Under Armour',
    author: '',
  },
  {
    id: 23,
    title: `Under Armour Women's Charged Pursuit 2 Running Shoe`,
    category: 'shoes',
    price: 10392,
    img: '../images/shoe3.jpg',
    desc: `Under Armour Women's Charged Pursuit 2 Running Shoe`,
    brand: 'Under Armour',
    author: '',
  },
  {
    id: 24,
    title: 'Under Armour Boys Running Shoe',
    category: 'shoes',
    price: 18291,
    img: '../images/shoe4.jpg',
    desc: `Under Armour Boys' Grade School Assert 9 Running Shoe`,
    brand: 'Under Armour',
    author: '',
  },
  {
    id: 25,
    title: 'Under Armour Basketball Shoe',
    category: 'shoes',
    price: 21202,
    img: '../images/shoe5.jpg',
    desc: `Under Armour Unisex-Child Grade School Jet '21 Basketball Shoe`,
    brand: 'Under Armour',
    author: '',
  },
  {
    id: 26,
    title: 'YAUEAI Boys Sneakers',
    category: 'shoes',
    price: 10393,
    img: '../images/shoe6.jpg',
    desc: `YAUEAI Boys Sneakers Tennis Athletic Running Walking Shoes Sock Shoes for Kids`,
    brand: 'YAUEAI',
    author: '',
  },
  {
    id: 27,
    title: 'BRONAX Men Sneakers',
    category: 'shoes',
    price: 16213,
    img: '../images/shoe7.jpg',
    desc: `BRONAX Men's Tennis Lightweight Athletics Gym Jogging Sneakers`,
    brand: 'BRONAX',
    author: '',
  },
  {
    id: 28,
    title: 'adidas Tennis Shoe',
    category: 'shoes',
    price: 8314,
    img: '../images/shoe8.jpg',
    desc: `adidas Unisex-Child Grand Court Tennis Shoe`,
    brand: 'adidas',
    author: '',
  },
  {
    id: 29,
    title: 'Under Armour Alternate Closure Running Shoe',
    category: 'shoes',
    price: 20786,
    img: '../images/shoe9.jpg',
    desc: `Under Armour Unisex-Child Pre-School Assert 9 Alternate Closure Running Shoe`,
    brand: 'Under Armour',
    author: '',
  },
  {
    id: 30,
    title: 'PromArder Toddler/Little Sneakers',
    category: 'shoes',
    price: 13303,
    img: '../images/shoe10.jpg',
    desc: `PromArder Toddler/Little Kid Boy Girl Shoes Tennis Running Sports Sneakers`,
    brand: 'PromArder',
    author: '',
  },
]
export default products;